#ifndef C_MANDELBROT_ARBITRARY_PRECISION_COLOR_H
#define C_MANDELBROT_ARBITRARY_PRECISION_COLOR_H

#define RBG_COLOR_SIZE sizeof(char) * 3

typedef char *rgb_color;

#endif //C_MANDELBROT_ARBITRARY_PRECISION_COLOR_H
